### PR TITLE
Add support for multiple model files.

### PR DESCRIPTION
**Pull request by JaxTheWolf**
I really like this script and thought "What if I have more printers I'd like to use this script with?" or, "Maybe I could tune in different nozzle sizes..". The first argument should be the model file, if left blank it should default to "model.txt".
Anyways, I'm not much of a C# programmer, but I tried to do my best. It seems to be working, though feel free to edit my PR as you see fit.

### CODE REVIEW

**Comment by Alexander-T-Moss** [comment]
Looks great, just double checking I understand you right, so if in the slicer you pass the path to the script, with no arguments (like it is atm), it will use the model.txt file for the model, then if you pass an argument (I'm assuming just the name of the model? or is it the path to the different model file?) then it will use that instead?

**Comment by JaxTheWolf** [comment]
It's actually a bit more problematic than I thought. I hadn't tested the script thoroughly enough yesterday and came across some issues. I'll take a look at it

**Comment by JaxTheWolf** [comment]
@Alexander-T-Moss sorry for dodging your question, in a way. With my current implementation it seems like the model name **must** be passed, else the script throws an error (3)

**Comment by JaxTheWolf** [comment]
The latest commit should retain the old functionality.

**Comment by JaxTheWolf** [comment]
Thanks!

**Pull request merged**
